# Generated by Django 4.1.3 on 2022-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('branch', models.CharField(max_length=98)),
                ('hall_ticket', models.CharField(max_length=10)),
                ('sem_grade', models.CharField(max_length=10)),
            ],
        ),
    ]
